# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5417496706527c5f8009831283238350db15bde5587602f1d5c09fd134967ec836f68c2d1e725aabd523bb99ddafdeb50d7e96cc89067889db424de90b72285c

test:
  secret_key_base: 758e5d9035c16c32043b39ed76f80ada72b088b92d73b918c8836cc57e9e345d0756f0b0ba456990433fa7fed66377816c683d47781d759ed64d4d138d5815eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
